### PR TITLE
add tests for midas open

### PR DESCRIPTION
**Pull request by faysal-ishtiaq**
I wanted to add more test for daily data but it seems we need to do some work in pyopencdms package first.

### CODE REVIEW

**Comment by isedwards** [comment]
Would it make sense to create the extra tests as failing tests initially and then update pyopencdms to make them pass?

**Comment by faysal-ishtiaq** [comment]
@isedwards 

I added a few extra tests which are failing. And according to this line: https://github.com/opencdms/pyopencdms/blob/aa9c037d40814eeeafe41b0638f240ada7702bda/opencdms/provider/midas.py#L56
, looks like we have to create a dictionary of column names, period and filename. We could write a script to generate this dictionary once we can point out which are the common fields that do not hold observation data in each csv files.

**Comment by isedwards** [comment]
Could you add mappings for `'max_air_temp'`, `'min_air_temp'`, `'glbl_irad_amt'`, `'difu_irad_amt'`, `'q5cm_soil_temp'` and `'q10cm_soil_temp'` in [`element_lookup`](https://github.com/opencdms/pyopencdms/blob/aa9c037d40814eeeafe41b0638f240ada7702bda/opencdms/provider/midas.py#L56) and also check that it's okay to uncomment `'mean_wind_speed'`, `'mean_wind_dir'` and `'prcp_amt'`? (I'm not sure why they are currently commented).

**Comment by faysal-ishtiaq** [comment]
@isedwards 

I tried to apply these filters for hourly rain data

```python
filters = {
        'src_id': 838,
        'period': 'hourly',
        'year': 1991,
        'elements': ['prcp_amt'],
    }
```

It returns this error `ValueError: Usecols do not match columns, columns expected but not found: ['ob_time']` because there is no column named `ob_time` for this csv file. But there is `ob_end_time`

for following filters
```python
filters = {
        'src_id': 838,
        'period': 'daily',
        'year': 1991,
        'elements': ['prcp_amt'],
    }
```

same error as previous one because there is `ob_date` and `ob_end_time` but not `ob_time`

These filters raises same error 
```python
filters = {
        'src_id': 838,
        'period': 'daily',
        'year': 1991,
        'elements': ['max_air_temp', 'min_air_temp'],
    }
```
for the respective csv file there is `ob_end_time`

same error for these filters
```python
filters = {
        'src_id': 838,
        'period': 'daily',
        'year': 1991,
        'elements': ['glbl_irad_amt', 'difu_irad_amt'],
    }
```

there is `ob_end_time` column though

for the following filters it works as there is `ob_time` column in the csv file. 
```python
filters = {
        'src_id': 838,
        'period': 'daily',
        'year': 1991,
        'elements': ['q5cm_soil_temp', 'q10cm_soil_temp'],
    }
```

Since the values in `q5cm_soil_temp` and `q10cm_soil_temp` columns are `NA` in the csv file, it returns `NaN` for these columns

I think we need to create and use a `date_time_column_lookup` here 

```python
read_badc(filepath, usecols=["src_id", "ob_time", *elements])
```

**Comment by isedwards** [comment]
@faysal-ishtiaq - Yes, please create an additional lookup when you get the chance. 

`ob_time` is used when a measurement is taken at a specific time (e.g. a temperature reading taken instantaneously at 15:00:00). `ob_end_time` is used when the measurement relates to a period (e.g. maximum temperature observed over a full 24-hour period). In the second case, the time that is recorded is the time at the end of the period.

**Comment by faysal-ishtiaq** [comment]
In pyopencdms, I added a dictionary like this

```python

date_time_column_lookup = {
    'uk-daily-rain-obs': 'ob_date',
    'uk-daily-temperature-obs': 'ob_end_time',
    'uk-daily-weather-obs': 'ob_end_time',
    'uk-hourly-rain-obs': 'ob_end_time',
    'uk-hourly-weather-obs': 'ob_time',
    'uk-mean-wind-obs': 'ob_end_time',
    'uk-radiation-obs': 'ob_end_time',
    'uk-soil-temperature-obs': 'ob_time'
}
```

and used it like this 
```python
        ....
        return read_badc(filepath, usecols=["src_id", date_time_column_lookup[element_lookup[element][period]], *elements])
```

it resolved the date time column issue.

**Pull request merged**
