### PR TITLE
V0.1.0 dev model updates

### PR DESCRIPTION
**Pull request by david-i-berry**
Update of test data to be consistent with cdm data model in pyopencdms branch of the same name.

### CODE REVIEW

**Comment by isedwards** [comment]
@david-i-berry - can you remind me how this dataset differs from the very large version that you're uploading to S3?

**Comment by isedwards** [comment]
@david-i-berry Could you add a few more details in the README on what this sample dataset contains -number of stations (hosts), range of  years, number of observed properties ...).

Also, do you think we need to explain that a host is a station and an observed property is an element/parameter (for users coming from existing systems using different nomenclature)?

**Comment by isedwards** [comment]
Also - would you be happy to write a similar summary for the larger dataset in the S3 bucket and we can included it as a README in the bucket?

**Comment by david-i-berry** [comment]
> @david-i-berry - can you remind me how this dataset differs from the very large version that you're uploading to S3?

1 station vs 100 stations.

**Review by isedwards — APPROVED** [review]

**Pull request merged**
